package com.example.server.enums;

public enum Operation {
    LOGIN,
    REGISTER,
    DISCONNECT,
    GET_ALL_USERS,
    UPDATE_USER,
    DELETE_USER,
    ADD_USER,
    GET_ALL_DEPARTMENTS,
    ADD_DEPARTMENT,
    UPDATE_DEPARTMENT,
    CHECK_OTHER_SALARY_EXISTS,
    CHECK_SALARY_EXISTS,
    DELETE_DEPARTMENT,
    GET_ALL_EMPLOYEES,
    ADD_EMPLOYEE,
    SEARCH_EMPLOYEES,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    GET_ALL_EDUCATION_TYPES, ADD_EDUCATION_TYPE, UPDATE_EDUCATION_TYPE, DELETE_EDUCATION_TYPE,
    GET_ALL_SALARIES, ADD_SALARY, UPDATE_SALARY, DELETE_SALARY, FILTER_SALARIES,
    TRANSFER_USER_TO_EMPLOYEE
}
